CONFIG_NAME: uzhethpos
PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: "0"
TERMINAL_BLOCK_HASH: 0xa1dbebba81ad0a859408356560f5a350c524c46d6d87aa7785c5c5a9c4755ee3
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: 128
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16
MIN_GENESIS_TIME: 1727993068
GENESIS_FORK_VERSION: 0x42424242
GENESIS_DELAY: 90
ALTAIR_FORK_VERSION: 0x01000000
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x02000000
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x03000000
CAPELLA_FORK_EPOCH: 2
SECONDS_PER_SLOT: 2
SECONDS_PER_ETH1_BLOCK: 2
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 4
SLOTS_PER_EPOCH: 32
EPOCHS_PER_ETH1_VOTING_PERIOD: 5
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40
DEPOSIT_CHAIN_ID: 710
DEPOSIT_NETWORK_ID: 710
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
